---
- include: install.yml
  tags: ['install', 'borgbackup']

- include: borgbackup_server.yml
  when: borgbackup_server
  tags: borgbackup

- include: borgbackup_client.yml
  when: borgbackup_client
  tags: borgbackup

- include: do_backup.yml
  when: borgbackup_client
  tags: borgbackup

- debug: msg="Neither borgbackup_server nor borgbackup_client is enabled for this host"
  when: borgbackup_server == False and borgbackup_client == False
  tags: borgbackup
